# Generated by Django 5.1.6 on 2025-02-25 10:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('user', 'date', 'meal_type', 'food_item')},
        ),
    ]
