# Generated by Django 5.1.6 on 2025-03-04 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_meal_carbs_meal_fat_meal_protein'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='TDEECalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (little to no exercise)'), ('light', 'Light (1-3 days of exercise)'), ('moderate', 'Moderate (3-5 days of exercise)'), ('active', 'Active (6-7 days of exercise)'), ('very_active', 'Very Active (twice per day training)')], max_length=20)),
                ('tdee', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
