# Generated by Django 5.1.6 on 2025-03-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_meal_calories_tdeecalculator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdeecalculator',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary (little to no exercise)'), ('light', 'Light (1-3 days of exercise)'), ('moderate', 'Moderate (3-5 days of exercise)'), ('active', 'Active (6-7 days of exercise)'), ('very_active', 'Very Active (twice per day training)')], default='moderate', max_length=20),
        ),
        migrations.AlterField(
            model_name='tdeecalculator',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='tdeecalculator',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='tdeecalculator',
            name='height',
            field=models.FloatField(default=170.0),
        ),
        migrations.AlterField(
            model_name='tdeecalculator',
            name='weight',
            field=models.FloatField(default=70.0),
        ),
    ]
